vm_metrics <- tibble::tibble(
  level = c(
    rep("patch", 28),
    rep("class", 11)
  ),
  name = c(
    "area",
    "core area index",
    "circularity",
    "CIRCLE",
    "cohesion index",
    "compactness",
    "convexity",
    "core area",
    "detour index",
    "elongation",
    "euclidean nearest-neighbor distance",
    "equivalent rectangular index",
    "exchange index",
    "fractal dimension index",
    "fullness index",
    "girth index",
    "number of disjunct core area",
    "perimeter-area ratio",
    "perimeter index",
    "perim",
    "proximity index",
    "range index",
    "rectangularity",
    "roughness index",
    "SHAPE",
    "solidity",
    "sphericity",
    "squareness",
    #########################################
    "coefficient of variation of all patch areas at class level",
    "mean value of all patch areas at class level",
    "standard deviation of all patch areas at class level",
    "total area of each class",
    "coefficient of variation of core area index values at class level",
    "mean value of ratio of core area index at class level",
    "standard deviation of core area index values at class level",
    "mean value of circularity at class level",
    "coefficient of variation of CIRCLE values at class level",
    "mean value of ratio of CIRCLE at class level",
    "standard deviation of CIRCLE values at class level"
  ),
  short_name = c(
    "area",
    "cai",
    "circ",
    "circle",
    "coh_idx",
    "compact",
    "convex",
    "core",
    "detour_idx",
    "elong",
    "enn",
    "eri",
    "exchange_idx",
    "frac",
    "full_idx",
    "girth_idx",
    "ncore",
    "perarea",
    "perim_idx",
    "perim",
    "proxim_idx",
    "range_idx",
    "rect",
    "rough_idx",
    "shape",
    "solid",
    "sphere",
    "square",
    #########################################
    "area_cv",
    "area_mn",
    "area_sd",
    "ca",
    "cai_cv",
    "cai_mn",
    "cai_sd",
    "circ_mn",
    "circle_cv",
    "circle_mn",
    "circle_sd"
  ),
  function_name = c(
    "vm_p_area",
    "vm_p_cai",
    "vm_p_circ",
    "vm_p_circle",
    "vm_p_coh",
    "vm_p_comp",
    "vm_p_convex",
    "vm_p_core",
    "vm_p_detour",
    "vm_p_elong",
    "vm_p_enn",
    "vm_p_eri",
    "vm_p_exchange",
    "vm_p_frac",
    "vm_p_fullness",
    "vm_p_girth",
    "vm_p_ncore",
    "vm_p_perarea",
    "vm_p_perim_idx",
    "vm_p_perim",
    "vm_p_proxim",
    "vm_p_range",
    "vm_p_rect",
    "vm_p_rough",
    "vm_p_shape",
    "vm_p_solid",
    "vm_p_sphere",
    "vm_p_square",
    #########################################
    "vm_c_area_cv",
    "vm_c_area_mn",
    "vm_c_area_sd",
    "vm_c_ca",
    "vm_c_cai_cv",
    "vm_c_cai_mn",
    "vm_c_cai_sd",
    "vm_c_circ_mn",
    "vm_c_circle_cv",
    "vm_c_circle_mn",
    "vm_c_circle_sd"
  ),
  type = c(
    "area and edge metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "aggregation metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "area and edge metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    #########################################
    "area and edge metric",
    "area and edge metric",
    "area and edge metric",
    "area and edge metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric"
  ),
  description = c(
    "patch area",
    "ratio of the core area and the area in square meters",
    "ratio between area of polygon and area of equal-perimeter circle",
    "ratio between the patch area and the smallest circumscribing circle of the patch",
    "ratio of the average distance-squared among all points in an equal-area circle and the average distance-squared among all points in the shape",
    "form factor calculated from equation: sqrt(4 * area / pi) / perimeter",
    "ratio between perimeter of convex hull and perimeter of polygon",
    "core area in square meters",
    "ratio between perimeter of equal-area circle and perimeter of convex hull of polygon",
    "ratio between major and minor axis length",
    "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
    "ratio between perimeter of equal-area rectangle of shape and perimeter of shape",
    "share of the total area of the shape that is inside the equal-area circle around its centroid",
    "based on the patch perimeter and the patch area and describes the patch complexity",
    "ratio between the average fullness of small neighbourhoods (1% of area) in the shape and in its equal-area circle",
    "ratio between radius of maximum inscribed circle and radius of equal-area circle",
    "number of disjunct core areas",
    "ratio between the patch perimeter and area",
    "ratio between perimeter of equal-area circle and perimeter of polygon",
    "patch perimeter",
    "ratio between average distance from all points of equal-area circle to its center and average distance from all points of shape to its center",
    "ratio between diameter of equal-area circle and diameter of smallest circumscribing circle",
    "ratio between area of shape and area of minimum area bounding rectangle (MABR)",
    "index calculated from area and perimeter of shape, as well as from average distance from edge of shape to its centroid",
    "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
    "ratio between area of convex hull and area of polygon",
    "ratio between radius of maximum inscribed circle and minimum circumscribing circle",
    "ratio between perimeter of equal-area square of shape and perimeter of shape",
    #########################################
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
  )
)

write.csv(vm_metrics, "./metrics_list.csv", row.names = FALSE)
usethis::use_data(vm_metrics, overwrite = TRUE)
