vm_metrics <- tibble::tibble(
  level = c(
    rep("patch", 28),
    rep("class", 61),
    rep("landscape", 49)
  ),
  name = c(
    "area",
    "core area index",
    "circularity",
    "CIRCLE",
    "cohesion index",
    "compactness",
    "convexity",
    "core area",
    "detour index",
    "elongation",
    "euclidean nearest-neighbor distance",
    "equivalent rectangular index",
    "exchange index",
    "fractal dimension index",
    "fullness index",
    "girth index",
    "number of disjunct core area",
    "perimeter-area ratio",
    "perimeter index",
    "perimeter",
    "proximity index",
    "range index",
    "rectangularity",
    "roughness index",
    "SHAPE",
    "solidity",
    "sphericity",
    "squareness",
    #########################################
    "coefficient of variation of patch areas at class level",
    "mean value of patch areas at class level",
    "standard deviation of patch areas at class level",
    "total area of each class",
    "coefficient of variation of core area index values at class level",
    "mean value of core area index at class level",
    "standard deviation of core area index values at class level",
    "mean value of circularity at class level",
    "coefficient of variation of CIRCLE values at class level",
    "mean value of CIRCLE at class level",
    "standard deviation of CIRCLE values at class level",
    "mean value of cohesion index at class level",
    "mean value of compactness at class level",
    "mean value of convexity at class level",
    "coefficient of variation of core area values at class level",
    "mean value of core area at class level",
    "standard deviation of core area values at class level",
    "core area percentage of landscape in each class",
    "disjunct core area density of each class",
    "coefficient of variation of number of disjunct core areas in each class",
    "mean value of number of disjunct core areas in each class",
    "standard deviation of number of disjunct core areas in each class",
    "mean value of detour index at class level",
    "landscape division index of each class",
    "edge density of each class",
    "mean value of elongation at class level",
    "coefficient of variation of euclidean nearest-neighbor distance at class level",
    "mean value of euclidean nearest-neighbor distance at class level",
    "standard deviation of euclidean nearest-neighbor distance at class level",
    "mean value of equivalent rectangular index at class level",
    "mean value of exchange index at class level",
    "coefficient of variation of fractal dimension index at class level",
    "mean value of fractal dimension index at class level",
    "standard deviation of fractal dimension index at class level",
    "mean value of fullness index at class level",
    "fullness index of aggregated patches of each class",
    "mean value of girth index at class level",
    "largest patch index at class level",
    "landscape shape index at class level",
    "effective mesh size at class level",
    "number of disjunct core area in each class",
    "number of patches in each class",
    "patch density at class level",
    "coefficient of variation of perimeter-area ratio at class level",
    "mean value of perimeter-area ratio at class level",
    "standard deviation of perimeter-area ratio at class level",
    "mean value of perimeter index at class level",
    "percentage of landscape of class",
    "mean value of proximity index at class level",
    "mean value of range index at class level",
    "mean value of rectangularity at class level",
    "mean value of roughness index at class level",
    "coefficient of variation of shape index at class level",
    "mean value of shape index at class level",
    "standard deviation of shape index at class level",
    "mean value of solidity at class level",
    "mean value of sphercity at class level",
    "splitting index",
    "mean value of squareness at class level",
    "total core area of each class",
    "total edge length of each class",
    #########################################
    "mean value of patch areas at landscape level",
    "mean value of core area index at landscape level",
    "mean value of circularity at landscape level",
    "mean value of cohesion index at landscape level",
    "mean value of compactness at landscape level",
    "mean value of convexity at landscape level",
    "mean value of patch core areas at landscape level",
    "disjunct core area density of the landscape",
    "mean value of number of core areas in landscape",
    "mean value of detour index at landscape level",
    "division index of the landscape",
    "edge density of the landscape",
    "mean value of elongation at landscape level",
    "mean value of equivalent rectangular index at landscape level",
    "mean value of exchange index at landscape level",
    "mean value of fractal dimension index at landscape level",
    "mean value of fullness index at landscape level",
    "fullness index of aggregated patches of landscape",
    "mean value of girth index at landscape level",
    "largest patch index",
    "landscape shape index",
    "effective mesh size",
    "modified Simpson's diversity index",
    "modified Simpson's evenness index",
    "number of disjunct core area in the landscape",
    "number of patches in landscape",
    "perimeter-area fractal dimension",
    "patch density in the landscape",
    "mean value of perimeter-area ratio at landscape level",
    "mean value of perimeter index at landscape level",
    "patch richness",
    "patch richness density",
    "mean value of proximity index at landscape level",
    "mean value of range index at landscape level",
    "mean value of rectangularity at landscape level",
    "mean value of roughness index at landscape level",
    "relative patch richness",
    "mean value of shape index at landscape level",
    "Shannon's diversity index at landscape level",
    "Shannon's evenness index at landscape level",
    "Simpson's diversity index at landscape level",
    "Simpson's evenness index at landscape level",
    "mean value of solidity at landscape level",
    "mean value of sphercity at landscape level",
    "splitting index",
    "mean value of squareness at landscape level",
    "total area of the landscape",
    "total core area of the landscape",
    "total edge length in the landscape"
  ),
  short_name = c(
    "area",
    "cai",
    "circ",
    "circle",
    "coh_idx",
    "compact",
    "convex",
    "core",
    "detour_idx",
    "elong",
    "enn",
    "eri",
    "exchange_idx",
    "frac",
    "full_idx",
    "girth_idx",
    "ncore",
    "perarea",
    "perim_idx",
    "perim",
    "proxim_idx",
    "range_idx",
    "rect",
    "rough_idx",
    "shape",
    "solid",
    "sphere",
    "square",
    #########################################
    "area_cv",
    "area_mn",
    "area_sd",
    "ca",
    "cai_cv",
    "cai_mn",
    "cai_sd",
    "circ_mn",
    "circle_cv",
    "circle_mn",
    "circle_sd",
    "coh_mn",
    "comp_mn",
    "conv_mn",
    "core_cv",
    "core_mn",
    "core_sd",
    "cpland",
    "DCAD",
    "dcore_cv",
    "dcore_mn",
    "dcore_sd",
    "detour_mn",
    "division",
    "ED",
    "elong_mn",
    "enn_cv",
    "enn_mn",
    "enn_sd",
    "eri_mn",
    "exchange_mn",
    "frac_cv",
    "frac_mn",
    "frac_sd",
    "full_mn",
    "full_idx",
    "girth_mn",
    "lpi",
    "lsi",
    "mesh",
    "ndca",
    "np",
    "pd",
    "perarea_cv",
    "perarea_mn",
    "perarea_sd",
    "perim_mn",
    "pland",
    "proxim_mn",
    "range_mn",
    "rect_mn",
    "rough_mn",
    "shape_cv",
    "shape_mn",
    "shape_sd",
    "solid_mn",
    "sphere_mn",
    "split",
    "square_mn",
    "tca",
    "te",
    #########################################
    "area_mn",
    "cai_mn",
    "circ_mn",
    "coh_mn",
    "comp_mn",
    "conv_mn",
    "core_mn",
    "dcad",
    "dcore_mn",
    "detour_mn",
    "division",
    "ed",
    "elong_mn",
    "eri_mn",
    "exchange_mn",
    "frac_mn",
    "full_mn",
    "full_index",
    "girth_mn",
    "lpi",
    "lsi",
    "mesh",
    "msidi",
    "msiei",
    "ndca",
    "np",
    "pafrac",
    "pd",
    "perarea_mn",
    "perim_mn",
    "pr",
    "prd",
    "proxim_mn",
    "range_mn",
    "rect_mn",
    "rough_mn",
    "rpr",
    "shape_mn",
    "shdi",
    "shei",
    "sidi",
    "siei",
    "solid_mn",
    "sphere_mn",
    "split",
    "square_mn",
    "ta",
    "tca",
    "te"
  ),
  function_name = c(
    "vm_p_area",
    "vm_p_cai",
    "vm_p_circ",
    "vm_p_circle",
    "vm_p_coh",
    "vm_p_comp",
    "vm_p_convex",
    "vm_p_core",
    "vm_p_detour",
    "vm_p_elong",
    "vm_p_enn",
    "vm_p_eri",
    "vm_p_exchange",
    "vm_p_frac",
    "vm_p_fullness",
    "vm_p_girth",
    "vm_p_ncore",
    "vm_p_perarea",
    "vm_p_perim_idx",
    "vm_p_perim",
    "vm_p_proxim",
    "vm_p_range",
    "vm_p_rect",
    "vm_p_rough",
    "vm_p_shape",
    "vm_p_solid",
    "vm_p_sphere",
    "vm_p_square",
    #########################################
    "vm_c_area_cv",
    "vm_c_area_mn",
    "vm_c_area_sd",
    "vm_c_ca",
    "vm_c_cai_cv",
    "vm_c_cai_mn",
    "vm_c_cai_sd",
    "vm_c_circ_mn",
    "vm_c_circle_cv",
    "vm_c_circle_mn",
    "vm_c_circle_sd",
    "vm_c_coh_mn",
    "vm_c_comp_mn",
    "vm_c_convex_mn",
    "vm_c_core_cv",
    "vm_c_core_mn",
    "vm_c_core_sd",
    "vm_c_cpland",
    "vm_c_dcad",
    "vm_c_dcore_cv",
    "vm_c_dcore_mn",
    "vm_c_dcore_sd",
    "vm_c_detour_mn",
    "vm_c_division",
    "vm_c_ed",
    "vm_c_elong_mn",
    "vm_c_enn_cv",
    "vm_c_enn_mn",
    "vm_c_enn_sd",
    "vm_c_eri_mn",
    "vm_c_exchange_mn",
    "vm_c_frac_cv",
    "vm_c_frac_mn",
    "vm_c_frac_sd",
    "vm_c_fullness_mn",
    "vm_c_fullness",
    "vm_c_girth_mn",
    "vm_c_lpi",
    "vm_c_lsi",
    "vm_c_mesh",
    "vm_c_ndca",
    "vm_c_np",
    "vm_c_pd",
    "vm_c_perarea_cv",
    "vm_c_perarea_mn",
    "vm_c_perarea_sd",
    "vm_c_perim_idx_mn",
    "vm_c_pland",
    "vm_c_proxim_mn",
    "vm_c_range_mn",
    "vm_c_rect_mn",
    "vm_c_rough_mn",
    "vm_c_shape_cv",
    "vm_c_shape_mn",
    "vm_c_shape_sd",
    "vm_c_solid_mn",
    "vm_c_sphere_mn",
    "vm_c_split",
    "vm_c_square_mn",
    "vm_c_tca",
    "vm_c_te",
    #########################################
    "vm_l_area_mn",
    "vm_l_cai_mn",
    "vm_l_circ_mn",
    "vm_l_coh_mn",
    "vm_l_comp_mn",
    "vm_l_conv_mn",
    "vm_l_core_mn",
    "vm_l_dcad",
    "vm_l_dcore_mn",
    "vm_l_detour_mn",
    "vm_l_division",
    "vm_l_ed",
    "vm_l_elong_mn",
    "vm_l_eri_mn",
    "vm_l_exchange_mn",
    "vm_l_frac_mn",
    "vm_l_fullness_mn",
    "vm_l_fullness",
    "vm_l_girth_mn",
    "vm_l_lpi",
    "vm_l_lsi",
    "vm_l_mesh",
    "vm_l_msidi",
    "vm_l_msiei",
    "vm_l_ndca",
    "vm_l_np",
    "vm_l_pafrac",
    "vm_l_pd",
    "vm_l_perarea_mn",
    "vm_l_perim_idx_mn",
    "vm_l_pr",
    "vm_l_prd",
    "vm_l_proxim_mn",
    "vm_l_range_mn",
    "vm_l_rect_mn",
    "vm_l_rough_mn",
    "vm_l_rpr",
    "vm_l_shape_mn",
    "vm_l_shdi",
    "vm_l_shei",
    "vm_l_sidi",
    "vm_l_siei",
    "vm_l_solid_mn",
    "vm_l_sphere_mn",
    "vm_l_split",
    "vm_l_square_mn",
    "vm_l_ta",
    "vm_l_tca",
    "vm_l_te"
  ),
  type = c(
    "area and edge metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "aggregation metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "area and edge metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    #########################################
    "area and edge metric",
    "area and edge metric",
    "area and edge metric",
    "area and edge metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "shape metric",
    "aggregation metric",
    "area and edge metric",
    "shape metric",
    "aggregation metric",
    "aggregation metric",
    "aggregation metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "aggregation metric",
    "shape metric",
    "area and edge metric",
    "aggregation metric",
    "aggregation metric",
    "core area metric",
    "aggregation metric",
    "aggregation metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "area and edge metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "aggregation metric",
    "shape metric",
    "core area metric",
    "area and edge metric",
    #########################################
    "area and edge metric",
    "core area metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "core area metric",
    "core area metric",
    "core area metric",
    "shape metric",
    "aggregation metric",
    "area and edge metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "aggregation metric",
    "shape metric",
    "area and edge metric",
    "aggregation metric",
    "aggregation metric",
    "diversity metric",
    "diversity metric",
    "core area metric",
    "aggregation metric",
    "shape metric",
    "aggregation metric",
    "shape metric",
    "shape metric",
    "diversity metric",
    "diversity metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "shape metric",
    "diversity metric",
    "shape metric",
    "diversity metric",
    "diversity metric",
    "diversity metric",
    "diversity metric",
    "shape metric",
    "shape metric",
    "aggregation metric",
    "shape metric",
    "area and edge metric",
    "core area metric",
    "area and edge metric"
  ),
  description = c(
    "patch area in hectares",
    "ratio of the core area and the area in square meters",
    "ratio between area of polygon and area of equal-perimeter circle",
    "ratio between the patch area and the smallest circumscribing circle of the patch",
    "ratio of the average distance-squared among all points in an equal-area circle and the average distance-squared among all points in the shape",
    "form factor calculated from equation: sqrt(4 * area / pi) / perimeter",
    "ratio between perimeter of convex hull and perimeter of polygon",
    "core area in hectares",
    "ratio between perimeter of equal-area circle and perimeter of convex hull of polygon",
    "ratio between major and minor axis length",
    "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
    "ratio between perimeter of equal-area rectangle of shape and perimeter of shape",
    "share of the total area of the shape that is inside the equal-area circle around its centroid",
    "based on the patch perimeter and the patch area and describes the patch complexity",
    "ratio between the average fullness of small neighbourhoods (1% of area) in the shape and in its equal-area circle",
    "ratio between radius of maximum inscribed circle and radius of equal-area circle",
    "number of disjunct core areas",
    "ratio between the patch perimeter and area",
    "ratio between perimeter of equal-area circle and perimeter of polygon",
    "patch perimeter",
    "ratio between average distance from all points of equal-area circle to its center and average distance from all points of shape to its center",
    "ratio between diameter of equal-area circle and diameter of smallest circumscribing circle",
    "ratio between area of shape and area of minimum area bounding rectangle (MABR)",
    "index calculated from area and perimeter of shape, as well as from average distance from edge of shape to its centroid",
    "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
    "ratio between area of convex hull and area of polygon",
    "ratio between radius of maximum inscribed circle and minimum circumscribing circle",
    "ratio between perimeter of equal-area square of shape and perimeter of shape",
    #########################################
    "patch areas in hectares",
    "patch areas in hectares",
    "patch areas in hectares",
    "class areas in hectares",
    "ratio of the core area and the area",
    "ratio of the core area and the area",
    "ratio of the core area and the area",
    "ratio between area of polygon and area of equal-perimeter circle",
    "ratio between the patch area and the smallest circumscribing circle of the patch",
    "ratio between the patch area and the smallest circumscribing circle of the patch",
    "ratio between the patch area and the smallest circumscribing circle of the patch",
    "ratio of the average distance-squared among all points in an equal-area circle and the average distance-squared among all points in the shape",
    "form factor calculated from equation: sqrt(4 * area / pi) / perimeter",
    "ratio between perimeter of convex hull and perimeter of polygon",
    "core area in hectares",
    "core area in hectares",
    "core area in hectares",
    "number of disjunct core areas per 100 ha relative to the total area",
    "-",
    "-",
    "-",
    "ratio between perimeter of equal-area circle and perimeter of convex hull of polygon",
    "sum of squared ratios between the patch area and class area",
    "sum of all edges of class in relation to the landscape area",
    "ratio between major and minor axis length",
    "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
    "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
    "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
    "ratio between perimeter of equal-area rectangle of shape and perimeter of shape",
    "share of the total area of the shape that is inside the equal-area circle around its centroid",
    "based on the patch perimeter and the patch area and describes the patch complexity",
    "based on the patch perimeter and the patch area and describes the patch complexity",
    "based on the patch perimeter and the patch area and describes the patch complexity",
    "ratio between the average fullness of small neighbourhoods (1% of area) in the shape and in its equal-area circle",
    "ratio between the average fullness of small neighbourhoods (1% of area) in the aggregated patches of the class and in their equal-area circle",
    "ratio between radius of maximum inscribed circle and radius of equal-area circle",
    "percentage of the landscape covered by the corresponding largest patch of each class",
    "ratio between the actual edge length of class and the hypothetical minimum edge length of class",
    "-",
    "-",
    "-",
    "-",
    "number of patches in class standardized to the area of class",
    "ratio between the patch perimeter and area",
    "ratio between the patch perimeter and area",
    "ratio between the patch perimeter and area",
    "ratio between perimeter of equal-area circle and perimeter of polygon",
    "-",
    "ratio between average distance from all points of equal-area circle to its center and average distance from all points of shape to its center",
    "ratio between diameter of equal-area circle and diameter of smallest circumscribing circle",
    "ratio between area of shape and area of minimum area bounding rectangle (MABR)",
    "index calculated from area and perimeter of shape, as well as from average distance from edge of shape to its centroid",
    "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
    "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
    "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
    "ratio between area of convex hull and area of polygon",
    "ratio between radius of maximum inscribed circle and minimum circumscribing circle",
    "number of patches if all patches of class would be divided into equally sized patches",
    "ratio between perimeter of equal-area square of shape and perimeter of shape",
    "-",
    "-",
    #########################################
    "patch areas in hectares",
    "ratio of the core area and the area",
    "ratio between area of polygon and area of equal-perimeter circle",
    "ratio of the average distance-squared among all points in an equal-area circle and the average distance-squared among all points in the shape",
    "form factor calculated from equation: sqrt(4 * area / pi) / perimeter",
    "ratio between perimeter of convex hull and perimeter of polygon",
    "core area in hectares",
    "number of disjunct core areas per 100 ha relative to the total area",
    "-",
    "ratio between perimeter of equal-area circle and perimeter of convex hull of polygon",
    "sum of squared ratios between the patch area and landscape area",
    "sum of all edges in relation to the landscape area",
    "ratio between major and minor axis length",
    "ratio between perimeter of equal-area rectangle of shape and perimeter of shape",
    "share of the total area of the shape that is inside the equal-area circle around its centroid",
    "based on the patch perimeter and the patch area and describes the patch complexity",
    "ratio between the average fullness of small neighbourhoods (1% of area) in the shape and in its equal-area circle",
    "ratio between the average fullness of small neighbourhoods (1% of area) in the aggregated patches of the landscape and in its equal-area circle",
    "ratio between radius of maximum inscribed circle and radius of equal-area circle",
    "percentage of the landscape covered by the largest patch in the landscape",
    "ratio between the actual landscape edge length and the hypothetical minimum edge length",
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "number of patches in landscape standardized to the area of that landscape",
    "ratio between the patch perimeter and area",
    "ratio between perimeter of equal-area circle and perimeter of polygon",
    "number of classes in the landscape",
    "number of classes in landscape standardized to the area of that landscape",
    "ratio between average distance from all points of equal-area circle to its center and average distance from all points of shape to its center",
    "ratio between diameter of equal-area circle and diameter of smallest circumscribing circle",
    "ratio between area of shape and area of minimum area bounding rectangle (MABR)",
    "index calculated from area and perimeter of shape, as well as from average distance from edge of shape to its centroid",
    "percentage of present classes in the landscape in relation to a (theoretical) number of maximum classes",
    "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
    "-",
    "-",
    "-",
    "-",
    "ratio between area of convex hull and area of polygon",
    "ratio between radius of maximum inscribed circle and minimum circumscribing circle",
    "number of patches if all patches the landscape would be divided into equally sized patches",
    "ratio between perimeter of equal-area square of shape and perimeter of shape",
    "landscape area in hectares",
    "core areas in hectares",
    "-"
  )
)

write.csv(vm_metrics, "./metrics_list.csv", row.names = FALSE)
usethis::use_data(vm_metrics, overwrite = TRUE)
