vm_metrics <- tibble::tribble(
  ~level, ~name, ~short_name, ~function_name, ~type, ~description,
  "patch", "area", "area", "vm_p_area", "area and edge metric", "patch area in hectares",
  "patch", "core area index", "cai", "vm_p_cai", "core area metric", "ratio of the core area and the area in square meters",
  "patch", "circularity", "circ", "vm_p_circ", "shape metric", "ratio between area of polygon and area of equal-perimeter circle",
  "patch", "CIRCLE", "circle", "vm_p_circle", "shape metric", "ratio between the patch area and the smallest circumscribing circle of the patch",
  "patch", "cohesion index", "coh_idx", "vm_p_coh", "shape metric", "ratio of the average distance-squared among all points in an equal-area circle and the average distance-squared among all points in the shape",
  "patch", "compactness", "compact", "vm_p_comp", "shape metric", "form factor calculated from equation: sqrt(4 * area / pi) / perimeter",
  "patch", "convexity", "convex", "vm_p_convex", "shape metric", "ratio between perimeter of convex hull and perimeter of polygon",
  "patch", "core area", "core", "vm_p_core", "core area metric", "core area in hectares",
  "patch", "detour index", "detour_idx", "vm_p_detour", "shape metric", "ratio between perimeter of equal-area circle and perimeter of convex hull of polygon",
  "patch", "elongation", "elong", "vm_p_elong", "shape metric", "ratio between major and minor axis length",
  "patch", "euclidean nearest-neighbor distance", "enn", "vm_p_enn", "aggregation metric", "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
  "patch", "equivalent rectangular index", "eri", "vm_p_eri", "shape metric", "ratio between perimeter of equal-area rectangle of shape and perimeter of shape",
  "patch", "exchange index", "exchange_idx", "vm_p_exchange", "shape metric", "share of the total area of the shape that is inside the equal-area circle around its centroid",
  "patch", "fractal dimension index", "frac", "vm_p_frac", "shape metric", "based on the patch perimeter and the patch area and describes the patch complexity",
  "patch", "fullness index", "full_idx", "vm_p_fullness", "shape metric", "ratio between the average fullness of small neighbourhoods (1% of area) in the shape and in its equal-area circle",
  "patch", "girth index", "girth_idx", "vm_p_girth", "shape metric", "ratio between radius of maximum inscribed circle and radius of equal-area circle",
  "patch", "number of disjunct core area", "ncore", "vm_p_ncore", "core area metric", "number of disjunct core areas",
  "patch", "perimeter-area ratio", "perarea", "vm_p_perarea", "shape metric", "ratio between the patch perimeter and area",
  "patch", "perimeter index", "perim_idx", "vm_p_perim_idx", "shape metric", "ratio between perimeter of equal-area circle and perimeter of polygon",
  "patch", "perimeter", "perim", "vm_p_perim", "area and edge metric", "patch perimeter",
  "patch", "proximity index", "proxim_idx", "vm_p_proxim", "shape metric", "ratio between average distance from all points of equal-area circle to its center and average distance from all points of shape to its center",
  "patch", "range index", "range_idx", "vm_p_range", "shape metric", "ratio between diameter of equal-area circle and diameter of smallest circumscribing circle",
  "patch", "rectangularity", "rect", "vm_p_rect", "shape metric", "ratio between area of shape and area of minimum area bounding rectangle (MABR)",
  "patch", "roughness index", "rough_idx", "vm_p_rough", "shape metric", "index calculated from area and perimeter of shape, as well as from average distance from edge of shape to its centroid",
  "patch", "SHAPE", "shape", "vm_p_shape", "shape metric", "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
  "patch", "solidity", "solid", "vm_p_solid", "shape metric", "ratio between area of convex hull and area of polygon",
  "patch", "sphericity", "sphere", "vm_p_sphere", "shape metric", "ratio between radius of maximum inscribed circle and minimum circumscribing circle",
  "patch", "squareness", "square", "vm_p_square", "shape metric", "ratio between perimeter of equal-area square of shape and perimeter of shape",
  "class", "coefficient of variation of patch areas at class level", "area_cv", "vm_c_area_cv", "area and edge metric", "patch areas in hectares",
  "class", "mean value of patch areas at class level", "area_mn", "vm_c_area_mn", "area and edge metric", "patch areas in hectares",
  "class", "standard deviation of patch areas at class level", "area_sd", "vm_c_area_sd", "area and edge metric", "patch areas in hectares",
  "class", "total area of each class", "ca", "vm_c_ca", "area and edge metric", "class areas in hectares",
  "class", "coefficient of variation of core area index values at class level", "cai_cv", "vm_c_cai_cv", "core area metric", "ratio of the core area and the area",
  "class", "mean value of core area index at class level", "cai_mn", "vm_c_cai_mn", "core area metric", "ratio of the core area and the area",
  "class", "standard deviation of core area index values at class level", "cai_sd", "vm_c_cai_sd", "core area metric", "ratio of the core area and the area",
  "class", "mean value of circularity at class level", "circ_mn", "vm_c_circ_mn", "shape metric", "ratio between area of polygon and area of equal-perimeter circle",
  "class", "coefficient of variation of CIRCLE values at class level", "circle_cv", "vm_c_circle_cv", "shape metric", "ratio between the patch area and the smallest circumscribing circle of the patch",
  "class", "mean value of CIRCLE at class level", "circle_mn", "vm_c_circle_mn", "shape metric", "ratio between the patch area and the smallest circumscribing circle of the patch",
  "class", "standard deviation of CIRCLE values at class level", "circle_sd", "vm_c_circle_sd", "shape metric", "ratio between the patch area and the smallest circumscribing circle of the patch",
  "class", "mean value of cohesion index at class level", "coh_mn", "vm_c_coh_mn", "shape metric", "ratio of the average distance-squared among all points in an equal-area circle and the average distance-squared among all points in the shape",
  "class", "mean value of compactness at class level", "comp_mn", "vm_c_comp_mn", "shape metric", "form factor calculated from equation: sqrt(4 * area / pi) / perimeter",
  "class", "mean value of convexity at class level", "conv_mn", "vm_c_convex_mn", "shape metric", "ratio between perimeter of convex hull and perimeter of polygon",
  "class", "coefficient of variation of core area values at class level", "core_cv", "vm_c_core_cv", "core area metric", "core area in hectares",
  "class", "mean value of core area at class level", "core_mn", "vm_c_core_mn", "core area metric", "core area in hectares",
  "class", "standard deviation of core area values at class level", "core_sd", "vm_c_core_sd", "core area metric", "core area in hectares",
  "class", "core area percentage of landscape in each class", "cpland", "vm_c_cpland", "core area metric", "total core area of each class in relation to landscape area",
  "class", "disjunct core area density of each class", "DCAD", "vm_c_dcad", "core area metric", "number of disjunct core areas per 100 ha relative to the total area",
  "class", "coefficient of variation of number of disjunct core areas in each class", "dcore_cv", "vm_c_dcore_cv", "core area metric", "-",
  "class", "mean value of number of disjunct core areas in each class", "dcore_mn", "vm_c_dcore_mn", "core area metric", "-",
  "class", "standard deviation of number of disjunct core areas in each class", "dcore_sd", "vm_c_dcore_sd", "core area metric", "-",
  "class", "mean value of detour index at class level", "detour_mn", "vm_c_detour_mn", "shape metric", "ratio between perimeter of equal-area circle and perimeter of convex hull of polygon",
  "class", "landscape division index of each class", "division", "vm_c_division", "aggregation metric", "sum of squared ratios between the patch area and class area",
  "class", "edge density of each class", "ED", "vm_c_ed", "area and edge metric", "sum of all edges of class in relation to the landscape area",
  "class", "mean value of elongation at class level", "elong_mn", "vm_c_elong_mn", "shape metric", "ratio between major and minor axis length",
  "class", "coefficient of variation of euclidean nearest-neighbor distance at class level", "enn_cv", "vm_c_enn_cv", "aggregation metric", "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
  "class", "mean value of euclidean nearest-neighbor distance at class level", "enn_mn", "vm_c_enn_mn", "aggregation metric", "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
  "class", "standard deviation of euclidean nearest-neighbor distance at class level", "enn_sd", "vm_c_enn_sd", "aggregation metric", "edge-to-edge distance to the nearest neighbouring patch of the same class in meters",
  "class", "mean value of equivalent rectangular index at class level", "eri_mn", "vm_c_eri_mn", "shape metric", "ratio between perimeter of equal-area rectangle of shape and perimeter of shape",
  "class", "mean value of exchange index at class level", "exchange_mn", "vm_c_exchange_mn", "shape metric", "share of the total area of the shape that is inside the equal-area circle around its centroid",
  "class", "coefficient of variation of fractal dimension index at class level", "frac_cv", "vm_c_frac_cv", "shape metric", "based on the patch perimeter and the patch area and describes the patch complexity",
  "class", "mean value of fractal dimension index at class level", "frac_mn", "vm_c_frac_mn", "shape metric", "based on the patch perimeter and the patch area and describes the patch complexity",
  "class", "standard deviation of fractal dimension index at class level", "frac_sd", "vm_c_frac_sd", "shape metric", "based on the patch perimeter and the patch area and describes the patch complexity",
  "class", "mean value of fullness index at class level", "full_mn", "vm_c_fullness_mn", "shape metric", "ratio between the average fullness of small neighbourhoods (1% of area) in the shape and in its equal-area circle",
  "class", "fullness index of aggregated patches of each class", "full_idx", "vm_c_fullness", "aggregation metric", "ratio between the average fullness of small neighbourhoods (1% of area) in the aggregated patches of the class and in their equal-area circle",
  "class", "mean value of girth index at class level", "girth_mn", "vm_c_girth_mn", "shape metric", "ratio between radius of maximum inscribed circle and radius of equal-area circle",
  "class", "largest patch index at class level", "lpi", "vm_c_lpi", "area and edge metric", "percentage of the landscape covered by the corresponding largest patch of each class",
  "class", "landscape shape index at class level", "lsi", "vm_c_lsi", "aggregation metric", "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
  "class", "effective mesh size at class level", "mesh", "vm_c_mesh", "aggregation metric", "-",
  "class", "number of disjunct core area in each class", "ndca", "vm_c_ndca", "core area metric", "number of disjunct core areas",
  "class", "number of patches in each class", "np", "vm_c_np", "aggregation metric", "number of patches",
  "class", "patch density at class level", "pd", "vm_c_pd", "aggregation metric", "number of patches in class standardized to the area of class",
  "class", "coefficient of variation of perimeter-area ratio at class level", "perarea_cv", "vm_c_perarea_cv", "shape metric", "ratio between the patch perimeter and area",
  "class", "mean value of perimeter-area ratio at class level", "perarea_mn", "vm_c_perarea_mn", "shape metric", "ratio between the patch perimeter and area",
  "class", "standard deviation of perimeter-area ratio at class level", "perarea_sd", "vm_c_perarea_sd", "shape metric", "ratio between the patch perimeter and area",
  "class", "mean value of perimeter index at class level", "perim_mn", "vm_c_perim_idx_mn", "shape metric", "ratio between perimeter of equal-area circle and perimeter of polygon",
  "class", "percentage of landscape of class", "pland", "vm_c_pland", "area and edge metric", "",
  "class", "mean value of proximity index at class level", "proxim_mn", "vm_c_proxim_mn", "shape metric", "ratio between average distance from all points of equal-area circle to its center and average distance from all points of shape to its center",
  "class", "mean value of range index at class level", "range_mn", "vm_c_range_mn", "shape metric", "ratio between diameter of equal-area circle and diameter of smallest circumscribing circle",
  "class", "mean value of rectangularity at class level", "rect_mn", "vm_c_rect_mn", "shape metric", "ratio between area of shape and area of minimum area bounding rectangle (MABR)",
  "class", "mean value of roughness index at class level", "rough_mn", "vm_c_rough_mn", "shape metric", "index calculated from area and perimeter of shape, as well as from average distance from edge of shape to its centroid",
  "class", "coefficient of variation of shape index at class level", "shape_cv", "vm_c_shape_cv", "shape metric", "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
  "class", "mean value of shape index at class level", "shape_mn", "vm_c_shape_mn", "shape metric", "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
  "class", "standard deviation of shape index at class level", "shape_sd", "vm_c_shape_sd", "shape metric", "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
  "class", "mean value of solidity at class level", "solid_mn", "vm_c_solid_mn", "shape metric", "ratio between area of convex hull and area of polygon",
  "class", "mean value of sphercity at class level", "sphere_mn", "vm_c_sphere_mn", "shape metric", "ratio between radius of maximum inscribed circle and minimum circumscribing circle",
  "class", "splitting index", "split", "vm_c_split", "aggregation metric", "number of patches if all patches of class would be divided into equally sized patches",
  "class", "mean value of squareness at class level", "square_mn", "vm_c_square_mn", "shape metric", "ratio between perimeter of equal-area square of shape and perimeter of shape",
  "class", "total core area of each class", "tca", "vm_c_tca", "core area metric", "core area in hectares",
  "class", "total edge length of each class", "te", "vm_c_te", "area and edge metric", "sum of all edges of class in meters",
  "landscape", "mean value of patch areas at landscape level", "area_mn", "vm_l_area_mn", "area and edge metric", "patch areas in hectares",
  "landscape", "mean value of core area index at landscape level", "cai_mn", "vm_l_cai_mn", "core area metric", "ratio of the core area and the area",
  "landscape", "mean value of circularity at landscape level", "circ_mn", "vm_l_circ_mn", "shape metric", "ratio between area of polygon and area of equal-perimeter circle",
  "landscape", "mean value of cohesion index at landscape level", "coh_mn", "vm_l_coh_mn", "shape metric", "ratio of the average distance-squared among all points in an equal-area circle and the average distance-squared among all points in the shape",
  "landscape", "mean value of compactness at landscape level", "comp_mn", "vm_l_comp_mn", "shape metric", "form factor calculated from equation: sqrt(4 * area / pi) / perimeter",
  "landscape", "mean value of convexity at landscape level", "conv_mn", "vm_l_conv_mn", "shape metric", "ratio between perimeter of convex hull and perimeter of polygon",
  "landscape", "mean value of patch core areas at landscape level", "core_mn", "vm_l_core_mn", "core area metric", "core area in hectares",
  "landscape", "disjunct core area density of the landscape", "dcad", "vm_l_dcad", "core area metric", "number of disjunct core areas per 100 ha relative to the total area",
  "landscape", "mean value of number of core areas in landscape", "dcore_mn", "vm_l_dcore_mn", "core area metric", "-",
  "landscape", "mean value of detour index at landscape level", "detour_mn", "vm_l_detour_mn", "shape metric", "ratio between perimeter of equal-area circle and perimeter of convex hull of polygon",
  "landscape", "division index of the landscape", "division", "vm_l_division", "aggregation metric", "sum of squared ratios between the patch area and class area",
  "landscape", "edge density of the landscape", "ed", "vm_l_ed", "area and edge metric", "sum of all edges of class in relation to the landscape area",
  "landscape", "mean value of elongation at landscape level", "elong_mn", "vm_l_elong_mn", "shape metric", "ratio between major and minor axis length",
  "landscape", "mean value of equivalent rectangular index at landscape level", "eri_mn", "vm_l_eri_mn", "shape metric", "ratio between perimeter of equal-area rectangle of shape and perimeter of shape",
  "landscape", "mean value of exchange index at landscape level", "exchange_mn", "vm_l_exchange_mn", "shape metric", "share of the total area of the shape that is inside the equal-area circle around its centroid",
  "landscape", "mean value of fractal dimension index at landscape level", "frac_mn", "vm_l_frac_mn", "shape metric", "based on the patch perimeter and the patch area and describes the patch complexity",
  "landscape", "mean value of fullness index at landscape level", "full_mn", "vm_l_fullness_mn", "shape metric", "ratio between the average fullness of small neighbourhoods (1% of area) in the shape and in its equal-area circle",
  "landscape", "fullness index of aggregated patches of landscape", "full_index", "vm_l_fullness", "aggregation metric", "ratio between the average fullness of small neighbourhoods (1% of area) in the aggregated patches of the landscape and in its equal-area circle",
  "landscape", "mean value of girth index at landscape level", "girth_mn", "vm_l_girth_mn", "shape metric", "ratio between radius of maximum inscribed circle and radius of equal-area circle",
  "landscape", "largest patch index", "lpi", "vm_l_lpi", "area and edge metric", "percentage of the landscape covered by the largest patch in the landscape",
  "landscape", "landscape shape index", "lsi", "vm_l_lsi", "aggregation metric", "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
  "landscape", "effective mesh size", "mesh", "vm_l_mesh", "aggregation metric", "-",
  "landscape", "modified Simpson's diversity index", "msidi", "vm_l_msidi", "diversity metric", "-",
  "landscape", "modified Simpson's evenness index", "msiei", "vm_l_msiei", "diversity metric", "-",
  "landscape", "number of disjunct core area in the landscape", "ndca", "vm_l_ndca", "core area metric", "number of disjunct core areas",
  "landscape", "number of patches in landscape", "np", "vm_l_np", "aggregation metric", "number of patches",
  "landscape", "perimeter-area fractal dimension", "pafrac", "vm_l_pafrac", "shape metric", "-",
  "landscape", "patch density in the landscape", "pd", "vm_l_pd", "aggregation metric", "number of patches in landscape standardized to the area of that landscape",
  "landscape", "mean value of perimeter-area ratio at landscape level", "perarea_mn", "vm_l_perarea_mn", "shape metric", "ratio between the patch perimeter and area",
  "landscape", "mean value of perimeter index at landscape level", "perim_mn", "vm_l_perim_mn", "shape metric", "ratio between perimeter of equal-area circle and perimeter of polygon",
  "landscape", "patch richness", "pr", "vm_l_pr", "diversity metric", "number of classes in the landscape",
  "landscape", "patch richness density", "prd", "vm_l_prd", "diversity metric", "number of classes in landscape standardized to the area of that landscape",
  "landscape", "mean value of proximity index at landscape level", "proxim_mn", "vm_l_proxim_mn", "shape metric", "ratio between average distance from all points of equal-area circle to its center and average distance from all points of shape to its center",
  "landscape", "mean value of range index at landscape level", "range_mn", "vm_l_range_mn", "shape metric", "ratio between diameter of equal-area circle and diameter of smallest circumscribing circle",
  "landscape", "mean value of rectangularity at landscape level", "rect_mn", "vm_l_rect_mn", "shape metric", "ratio between area of shape and area of minimum area bounding rectangle (MABR)",
  "landscape", "mean value of roughness index at landscape level", "rough_mn", "vm_l_rough_mn", "shape metric", "index calculated from area and perimeter of shape, as well as from average distance from edge of shape to its centroid",
  "landscape", "relative patch richness", "rpr", "vm_l_rpr", "diversity metric", "percentage of present classes in the landscape in relation to a (theoretical) number of maximum classes",
  "landscape", "mean value of shape index at landscape level", "shape_mn", "vm_l_shape_mn", "shape metric", "ratio between the actual perimeter of the patch and the hypothetical minimum perimeter of the patch",
  "landscape", "Shannon's diversity index at landscape level", "shdi", "vm_l_shdi", "diversity metric", "-",
  "landscape", "Shannon's evenness index at landscape level", "shei", "vm_l_shei", "diversity metric", "-",
  "landscape", "Simpson's diversity index at landscape level", "sidi", "vm_l_sidi", "diversity metric", "-",
  "landscape", "Simpson's evenness index at landscape level", "siei", "vm_l_siei", "diversity metric", "-",
  "landscape", "mean value of solidity at landscape level", "solid_mn", "vm_l_solid_mn", "shape metric", "ratio between area of convex hull and area of polygon",
  "landscape", "mean value of sphercity at landscape level", "sphere_mn", "vm_l_sphere_mn", "shape metric", "ratio between radius of maximum inscribed circle and minimum circumscribing circle",
  "landscape", "splitting index", "split", "vm_l_split", "aggregation metric", "number of patches if all patches the landscape would be divided into equally sized patches",
  "landscape", "mean value of squareness at landscape level", "square_mn", "vm_l_square_mn", "shape metric", "ratio between perimeter of equal-area square of shape and perimeter of shape",
  "landscape", "total area of the landscape", "ta", "vm_l_ta", "area and edge metric", "landscape area in hectares",
  "landscape", "total core area of the landscape", "tca", "vm_l_tca", "core area metric", "core area in hectares",
  "landscape", "total edge length in the landscape", "te", "vm_l_te", "area and edge metric", "sum of all edges of class in meters"
)

write.csv(vm_metrics, "./metrics_list.csv", row.names = FALSE)
usethis::use_data(vm_metrics, overwrite = TRUE)
