# Regression tests for vectormetrics metric implementations
# 
# These tests verify that vectormetrics metric functions produce consistent
# values over time by comparing current outputs against a baseline computed
# from data-raw/12_compute_metric_comparisons.R
#
# The baseline contains value_vm (vectormetrics) and value_lsm (landscapemetrics)
# but tests only check value_vm for consistency - we're testing vectormetrics
# implementations, not the comparison to landscapemetrics.
#
# If tests fail:
# 1. Determine if the change was intentional (code improvement/bug fix)
# 2. If intentional, regenerate baseline (see fixtures/README.md)
# 3. If unintentional, investigate what changed in the metric implementation

test_that("all vectormetrics metrics match baseline values", {
  skip_on_cran()  # Skip expensive tests on CRAN
  
  # Load baseline and test landscape from inst/extdata
  # Both generated by data-raw/12_compute_metric_comparisons.R
  baseline <- readRDS(system.file("extdata/vm_lsm_baseline.rds", package = "vectormetrics"))
  polygon_landscape <- readRDS(system.file("extdata/landscape_polygons.rds", package = "vectormetrics"))
  
  # Get unique vm functions from baseline
  vm_functions <- unique(baseline$all$vm_fun[!is.na(baseline$all$vm_fun)])
  
  # Test each metric function
  for (fn_name in vm_functions) {
    # Get expected values from baseline
    expected <- baseline$all |>
      dplyr::filter(vm_fun == !!fn_name) |>
      dplyr::select(patch_id, class, value_vm) |>
      dplyr::arrange(patch_id, class)
    
    # Skip if no baseline data
    if (nrow(expected) == 0) next
    
    # Call the function with appropriate arguments
    fn <- get(fn_name, mode = "function")
    fn_args <- names(formals(fn))
    
    call_args <- list(polygon_landscape)
    if ("class_col" %in% fn_args) call_args$class_col <- "class"
    if ("patch_col" %in% fn_args) call_args$patch_col <- "patch"
    if ("edge_depth" %in% fn_args) call_args$edge_depth <- 1
    if ("classes_max" %in% fn_args) call_args$classes_max <- 3
    
    current <- do.call(fn, call_args) |>
      dplyr::select(id, class, value) |>
      dplyr::rename(patch_id = id) |>
      dplyr::mutate(
        patch_id = as.character(patch_id),
        class = as.character(class)
      ) |>
      dplyr::arrange(patch_id, class)
    
    # Compare current to baseline
    expect_equal(
      current$value,
      expected$value_vm,
      tolerance = 1e-10,
      info = sprintf("Metric %s changed from baseline", fn_name)
    )
  }
})
